### PR TITLE
Add the guy!!!

### PR DESCRIPTION
**Pull request by lfv89**
Add the @eordano YUNO guy

### CODE REVIEW

**Comment by eordano** [comment]
Definitely, this should be a priority of the maintainer.

**Comment by knownasilya** [comment]
:+1: yes please!

**Comment by nisaacson** [comment]
Definitely needs to be added

**Comment by lfv89** [comment]
@eordano ???

**Comment by maraoz** [comment]
ACK

**Comment by maraoz** [comment]
:-1: disagree with this project's maintainers :angry:

**Pull request closed without merging**
